
on:
  schedule:
    - cron: "59 23 * * *"

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          exempt-issue-labels: pinned
          include-only-assigned: true
          days-before-pr-close: -1
          stale-pr-message: This PR is stale because it has been open 60 days with no activity.
          stale-issue-message:
            "This issue is stale because it has been open 60 days with no activity. Remove stale
            label or comment or this will be closed in 7 days."
          close-issue-message:
            "This issue was closed because it has been stalled for 7 days with no activity."

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: build (${{ matrix.os }})
    uses: hexagontk/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      check_directory: args/build
      ref: develop

  native_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: native_test (${{ matrix.os }})
    uses: hexagontk/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      tasks: nativeTest

  test_publishing:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: test_publishing (${{ matrix.os }})
    uses: hexagontk/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      check_directory: args/build
      tasks: publishToMavenLocal
