
name: Push

on:
  push:
    branches-ignore: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: hexagontk/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      check_directory: args/build
